#!/usr/bin/env bash

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
dry="0"

while [[ $# -gt 0 ]]; do
  if [[ "$1" == "--dry" ]]; then
    dry="1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $*"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $*"
  if [[ $dry == "1" ]]; then
    return
  fi

  "$@"
}

log "--------- dev-env ---------"

copy_dir() {
  log "copy_dir $*"
  from=$1
  to=$2
  pushd "$from" >/dev/null || return
  dirs=$(find . -maxdepth 1 -mindepth 1 -type d)
  for dir in $dirs; do
    execute rm -rf "$to/$dir"
    execute cp -r "$dir" "$to/$dir"
  done
  popd >/dev/null || return
}

copy_file() {
  log "copy_file $*"
  from=$1
  to=$2
  name=$(basename "$from")
  execute rm "$to/$name"
  execute cp "$from" "$to/$name"
}

copy_dir .config/nvim "$HOME/.config/nvim"
copy_dir .local "$HOME/.local"
