#!/usr/bin/env bash

VERSION=1.24.0
ARCHIVE_NAME=go$VERSION.linux-amd64.tar.gz
wget -O "/tmp/$ARCHIVE_NAME" "https://go.dev/dl/$ARCHIVE_NAME"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "/tmp/$ARCHIVE_NAME"
