#!/usr/bin/env bash

NVM_VERSION=v0.40.1
NODE_VERSION=v23.8.0

# nvm
export NVM_DIR="$HOME/.nvm"
rm -rf "$NVM_DIR"
git clone --depth 1 --branch "$NVM_VERSION" https://github.com/nvm-sh/nvm.git "$NVM_DIR"
cd "$NVM_DIR"
. "$NVM_DIR/nvm.sh"

# node
nvm install node "$NODE_VERSION"
nvm use node
