#!/usr/bin/env bash

PYENV_VERSION=v2.5.3
PYTHON_VERSION=3.13

# pyenv
rm -rf ~/.pyenv
git clone --depth 1 --branch "$PYENV_VERSION" https://github.com/pyenv/pyenv.git ~/.pyenv
cd ~/.pyenv && src/configure && make -C src

# python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
pyenv install "$PYTHON_VERSION"
pyenv global "$PYTHON_VERSION"
