#!/usr/bin/env bash

sudo apt update
sudo apt upgrade -y

#sudo apt install -y \
#  build-essential \
#  curl \
#  fd-find \
#  fzf \
#  jq \
#  libbz2-dev \
#  libffi-dev \
#  liblzma-dev \
#  libncursesw5-dev \
#  libreadline-dev \
#  libsqlite3-dev \
#  libssl-dev \
#  libxml2-dev \
#  libxmlsec1-dev \
#  python3 \
#  python3-pip \
#  python-is-python3 \
#  ripgrep \
#  stow \
#  tk-dev \
#  xz-utils \
#  zlib1g-dev \
#  zoxide \
#  zsh
